//! Browser-facing WebGL2 bindings generated by `wasm-bindgen`.

use wasm_bindgen::{prelude::wasm_bindgen, JsCast, JsValue};

use super::OpenGlRenderer;
use crate::{Composition, Limits, RenderOptions};

/// WebGL2 tlottie renderer bound directly to an HTML canvas.
///
/// `wasm-bindgen` exports this as `WebGlRenderer`; applications pass their
/// canvas object directly and do not need a handwritten tlottie JS shim.
#[wasm_bindgen(js_name = WebGlRenderer)]
pub struct WebGlRenderer {
  canvas: web_sys::HtmlCanvasElement,
  renderer: OpenGlRenderer,
}

#[wasm_bindgen(js_class = WebGlRenderer)]
impl WebGlRenderer {
  /// Parses Lottie JSON and creates a WebGL2 context on `canvas`.
  #[wasm_bindgen(constructor)]
  pub fn new(json: &[u8], canvas: web_sys::HtmlCanvasElement) -> core::result::Result<WebGlRenderer, JsValue> {
    let composition = Composition::parse(json, &Limits::default()).map_err(js_error)?;
    let value = canvas
      .get_context("webgl2")
      .map_err(|_| JsValue::from_str("canvas.getContext('webgl2') threw"))?
      .ok_or_else(|| JsValue::from_str("WebGL2 is unavailable for this canvas"))?;
    let webgl = value
      .dyn_into::<web_sys::WebGl2RenderingContext>()
      .map_err(|_| JsValue::from_str("canvas returned a non-WebGL2 context"))?;
    let gl = glow::Context::from_webgl2_context(webgl);
    // SAFETY: the context was synchronously created from this canvas and is
    // the browser's current WebGL context for all calls through `glow`.
    let renderer = unsafe { OpenGlRenderer::new(gl, composition) }.map_err(js_error)?;
    Ok(WebGlRenderer { canvas, renderer })
  }

  /// Composition width in pixels.
  #[wasm_bindgen(getter)]
  pub fn width(&self) -> u32 {
    self.renderer.composition().width
  }

  /// Composition height in pixels.
  #[wasm_bindgen(getter)]
  pub fn height(&self) -> u32 {
    self.renderer.composition().height
  }

  /// Composition frame rate.
  #[wasm_bindgen(getter, js_name = frameRate)]
  pub fn frame_rate(&self) -> f32 {
    self.renderer.composition().frame_rate
  }

  /// Number of animation frames.
  #[wasm_bindgen(getter, js_name = frameCount)]
  pub fn frame_count(&self) -> u32 {
    self.renderer.composition().frame_count()
  }

  /// Resizes the canvas drawing buffer, renders, uploads, and presents a frame.
  pub fn render(&mut self, frame: f32, width: u32, height: u32, antialias: bool) -> core::result::Result<(), JsValue> {
    self.render_with_options(frame, width, height, antialias, RenderOptions::default().curve_tolerance)
  }

  /// Renders with an explicit positive maximum curve-flattening error in
  /// device pixels.
  #[wasm_bindgen(js_name = renderWithOptions)]
  pub fn render_with_options(&mut self, frame: f32, width: u32, height: u32, antialias: bool, curve_tolerance: f32) -> core::result::Result<(), JsValue> {
    if !curve_tolerance.is_finite() || curve_tolerance <= 0.0 {
      return Err(JsValue::from_str("curve_tolerance must be finite and greater than zero"));
    }
    if self.canvas.width() != width {
      self.canvas.set_width(width);
    }
    if self.canvas.height() != height {
      self.canvas.set_height(height);
    }
    self
      .renderer
      .render(
        frame,
        width,
        height,
        RenderOptions {
          antialias,
          curve_tolerance,
          ..RenderOptions::default()
        },
      )
      .map_err(js_error)
  }
}

fn js_error(error: impl core::fmt::Display) -> JsValue {
  JsValue::from_str(&error.to_string())
}
